name: Worker deployment CI

on:
  workflow_run:
    workflows: ['Node.js CI']
    branches: [master]
    types:
      - completed

env:
  NODE_VERSION: 14.16.1
  DOCKER_IMAGE_NAME: resolution-service
  IMAGE_URL: gcr.io/${{ secrets.GCP_PROJECT_ID }}/resolution-service

jobs:
  deployment:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Docker
        uses: docker/build-push-action@v2.4.0

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure gcloud and docker auth
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: docker build -t ${{ env.DOCKER_IMAGE_NAME }} .

      - name: Tag image with container registry
        run: docker tag ${{ env.DOCKER_IMAGE_NAME }} ${{ env.IMAGE_URL }}

      - name: Deploy tagged image to container registry
        run: docker push ${{ env.IMAGE_URL }}

      - name: Deploy service
        run: gcloud run deploy resolution-service --image ${{ env.IMAGE_URL }}
